
// <auto-generated />
using System;
using CustomerLeadImages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CustomerLeadImages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("CustomerLeadImages.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CustomerLeadImages.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("CustomerLeadImages.Models.ProfileImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Base64Data")
                        .IsRequired();

                    b.Property<string>("Caption");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("MimeType")
                        .IsRequired();

                    b.Property<int>("OwnerId");

                    b.Property<string>("OwnerType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("ProfileImages");
                });
        }
    }
}
